// <auto-generated />
using Entity_Framework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(myapp))]
    [Migration("20221110080851_emtit")]
    partial class emtit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity_Framework.Models.Employee", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Department_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.Property<string>("departmentsdepartment_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("salary")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("departmentsdepartment_name");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Entity_Framework.Models.departments", b =>
                {
                    b.Property<string>("department_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.HasKey("department_name");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Entity_Framework.Models.Employee", b =>
                {
                    b.HasOne("Entity_Framework.Models.departments", null)
                        .WithMany("employees")
                        .HasForeignKey("departmentsdepartment_name");
                });

            modelBuilder.Entity("Entity_Framework.Models.departments", b =>
                {
                    b.Navigation("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
